[project]
name = "logicmate-backend"
version = "1.0.0"
description = "Interactive Assistance Bot Backend Server on Algorithm Programs and Programming Flowcharts for the course “Introduction to Algorithmics”"
authors = [
    { name = "Vladimir Curiel", email = "voco0001@ce.pucmm.edu.do" },
    { name = "Natasha López", email = "nmlc0001@ce.pucmm.edu.do" },
]
readme = "README.md"
requires-python = "==3.10.18"
dependencies = [
    "fastapi (==0.115.12)",
    "uvicorn[standard] (==0.34.2)",
    "ruff (==0.11.10)",
    "pyjwt (==2.10.1)",
    "motor (==3.7.1)",
    "python-dotenv (==1.1.1)",
    "passlib[bcrypt] (==1.7.4)",
    "celery (==5.3.6)",
    "redis (==5.0.1)",
    "flower (==2.0.1)",
    "python-multipart (==0.0.20)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
  { include = "logicmate_backend", from = "src" }
]